Agora-wireless/Agora

- data/data_generator/data_generator.cpp
- data/data_generator/data_generator.h
- data/tddconfig-sim-ul-distributed.json
- src/agora/dofft.cpp
- src/agora/dosubcarrier.hpp
- src/common/comms-lib-avx.cpp
- src/common/comms-lib.h
- src/common/shared_counters.hpp
- src/common/udp_server.h
- Add `dosubcarrier.hpp`, which handles all subcarrier-parallel processing
- Add `shared_counters.hpp`, which handles dependency tracking for tasks in a master-less mode we're developing
- These two files will be unused until we merge-in other changes from the distributed processing branch
- Use `CommsLib::__m256_complex_cf32_mult` instead of redefining it in `dofft.cpp`
> Partial set of changes from the distributed processing branch

- data/bs-dl-hw.json
- data/bs-ul-hw.json
- data/ue-dl-hw.json
- src/agora/dofft.cpp
- src/agora/txrx/txrx_argos.cpp
- src/client/phy-ue.cpp
- src/client/phy-ue.hpp
- src/client/txrx_client.cpp
- src/common/Symbols.hpp
- src/common/config.cpp
- src/common/config.hpp
- Fixes segfaults scheduler in Phy_UE downlink
- Bugfixes in Agora downlink (`dofft.cpp` and `txrx_agora.cpp`).
> Downlink Bugfixes in SDR mode

- data/bs-one-ul-hw.json
- src/agora/dodemul.cpp
- src/agora/txrx/txrx.cpp
- src/client/phy-ue.cpp
- src/common/modulation.hpp
- src/common/modulation_srslte.cpp
- Add QPSK support to both dowlink and uplink
- Fix a bug from previous PR that breaks uplink with hardware
> QPSK Support

- data/data_generator/data_generator.cpp
- data/data_generator/data_generator.h
- simulator/sender.cpp
- simulator/sender.hpp
- src/agora/docoding.cpp
- src/agora/phy_stats.cpp
- src/common/Symbols.hpp
- src/common/config.cpp
- test/compute_kernels/ldpc/test_ldpc_baseband.cpp
- test/compute_kernels/ldpc/test_ldpc_mod.cpp
Changed num_codeblocks to be equal to the number of UL symbols.
Also effected the size of information / encoded_codewords / modulated_codewords / pre_ifft_data_syms. 
Reindex the combine into tx_data_all_symbols.  
Do we need to do anything for DL_CAL and UL_CAL symbol types?
> Changed num_codeblocks to be equal to the number of UL symbols.

- Jenkinsfile
- README.md
Update Jenkinsfile for ul-dl-integration branch and unit tests
Closes #257
> Update Jenkinsfile for ul-dl-integration branch and unit tests

- README.md
- src/agora/docoding.cc
- src/agora/docoding.h
- src/client/phy-ue.cc
- src/client/phy-ue.h
- src/common/config.cc
- src/common/scrambler.cc
- src/common/scrambler.h
- src/data_generator/data_generator.cc
- test/unit_tests/test_scrambler.cc
Removed dynamic memory allocation out of the scrambler routines and added them to the class.
> Scrambler no dynamic mem

- README.md
- test/sim_tests/test_e2e_sim.sh
1. Change CI build status badge to falcon https
2. Fix a bug in test_e2e_sim.sh
Closes #270
> Change CI badge to falcon https, fix bug in test_e2e_sim

- README.md
- data/bs-mac-sim.json
- data/ue-mac-sim.json
- python/client_app.py
- src/agora/agora.cc
- src/client/phy-ue.cc
- src/common/config.cc
- src/common/config.h
- src/common/crc.h
- src/common/symbols.h
- src/mac/mac_thread.cc
- src/mac/mac_thread.h
Added initial support and instructions for the ENABLE_MAC=true uplink frame testing. 
Memory cleanup of the mac_thread and related allocations
> Pr enable mac ul test

- Jenkinsfile
- README.md
Add a feature to prevent concurrent CI builds/tests. 
Closes #278
> Concurrent ci

- README.md
- src/client/phy-ue.cc
- src/client/phy-ue.h
- src/common/config.cc
- src/common/udp_server.h
Bugfix for MacPacket data alignment issues caused by padded the packet to help with alignment warnings.
> Fixed data misalignment with the MacPacket padding.

- README.md
- simulator/sender.cc
Made a mistake in the last pr with the sender time stamps.
> Pr sendertime fix

- Agora_doxygen.conf
- README.md
> Pr reldocs fixes

- src/common/buffer.h
- src/mac/file_receiver.h
- src/mac/mac_data_receiver.h
- src/mac/video_receiver.h
> Fixed compiler warnings

- src/client/phy-ue.cc
- src/client/phy-ue.h
- src/client/txrx_client.cc
- src/client/txrx_client.h
- src/common/config.cc
Closing #326 
Patch fix for hardware testing with multiple UE.  Verified with UL frames.
> Patch for testing the UE > 1 bug in Argos mode.

- src/agora/txrx/txrx.cc
- src/client/phy-ue.cc
- src/client/phy-ue.h
- src/client/txrx_client.cc
- src/client/txrx_client.h
- src/common/config.cc
Merging bugfix from master
closing #326
> Pr ue bugfix develop

- src/agora/agora.cc
Bugfix for the encoding deferral
> Bugfix for defferal frames

- src/agora/radio_calibrate_digital.cc
- src/common/comms-lib.cc
- src/common/comms-lib.h
- src/common/memory_manage.h
Discussion items.  Suggest to merge dual FFT and iFFT functions (call 1 from the other)
> Modified the parameters of many commlib functions

- CMakeLists.txt
- src/agora/agora.cc
- src/agora/agora.h
- src/agora/dozf.cc
- src/agora/dozf.h
- src/agora/phy_stats.cc
- src/agora/phy_stats.h
- src/client/phy-ue.cc
- src/client/phy-ue.h
- src/client/ue_worker.cc
- src/client/ue_worker.h
- src/common/csv_logger.cc
- src/common/csv_logger.h
- src/common/mat_logger.cc
- src/common/mat_logger.h
- test/unit_tests/test_zf.cc
- test/unit_tests/test_zf_threaded.cc
Simplified the interface, moved the buffers inside the mat logger class.
> Log plot mods

- simulator/channel_sim.cc
- simulator/channel_sim.h
- simulator/sender.cc
- simulator/sender.h
- src/agora/doifft.cc
- src/agora/radio/radio_calibrate_digital.cc
- src/client/doifft_client.cc
- src/client/phy-ue.cc
- src/client/phy-ue.h
- src/client/txrx/workers/txrx_worker_client_hw.cc
- src/client/ue_worker.cc
- src/client/ue_worker.h
- src/common/comms-lib-avx.cc
- src/common/comms-lib.cc
- src/common/config.cc
- src/common/datatype_conversion.h
- src/common/simd_types.h
- src/common/utils.cc
- src/data_generator/data_generator.cc
- test/compute_kernels/ldpc/test_ldpc_mod.cc
- test/compute_kernels/test_fft_mkl.cc
- test/compute_kernels/test_transpose.cc
- test/test_agora/main.cc
- test/unit_tests/test_datatype_conversion.cc
Updated the data type conversion functions
> datatype conv Float<->Short

- src/agora/txrx/packet_txrx.cc
- src/agora/txrx/packet_txrx_dpdk.cc
- src/agora/txrx/workers/txrx_worker_dpdk.cc
Fixed a bug in the tid dpdk worker selection
> Dpdk lcore mods

- src/agora/doencode.cc
- src/client/txrx/workers/txrx_worker_client_hw.cc
- src/client/ue_worker.cc
- src/common/config.cc
- src/common/config.h
- src/common/scrambler.cc
- src/common/scrambler.h
- src/common/symbols.h
- src/data_generator/data_generator.cc
- test/unit_tests/test_scrambler.cc
Zero'd unused memory for the scrambler buffer. 
Added memcheck for debugging
> Scrambler const input

- src/agora/radio/radio_data_plane_soapy.cc
- src/agora/radio/radio_data_plane_socket.cc
- src/agora/radio/radio_soapysdr.cc
- src/agora/txrx/workers/txrx_worker.cc
- src/agora/txrx/workers/txrx_worker.h
- src/agora/txrx/workers/txrx_worker_dpdk.cc
- src/agora/txrx/workers/txrx_worker_hw.cc
- src/agora/txrx/workers/txrx_worker_sim.cc
- src/agora/txrx/workers/txrx_worker_usrp.cc
- src/client/txrx/workers/txrx_worker_client_hw.cc
- src/client/txrx/workers/txrx_worker_client_hw.h
- src/client/txrx/workers/txrx_worker_client_sim.cc
> Client txflags

- src/client/txrx/workers/txrx_worker_client_hw.cc
- src/client/txrx/workers/txrx_worker_client_hw.h
- src/common/comms-lib.h
- test/radio_test/main.cc
Use the scaling parameter for the initial beacon detect of the Ue
> Fix scaling of initial beacon detect

- src/agora/agora.cc
- src/agora/dobeamweights.cc
- src/agora/dobeamweights.h
- src/agora/doer.h
- src/agora/stats.cc
- src/common/config.cc
- src/common/config.h
- test/unit_tests/test_zf_threaded.cc
> Freq orth review

- src/agora/agora.cc
- src/agora/stats.cc
- src/agora/stats.h
- src/common/utils.cc
> bugfix for mac ul
